### ISSUE TITLE
Malisis Doors still crashing with DragonAPI & ChromatiCraft

### ISSUE THREAD

**Issue by Eliteneet** [Beyond-Reality/Beyond-Reality-Divergence#144]
DragonAPI V9b
ChromatiCraft V9b
Malisis Core 0.12.9
Malisis Doors 1.10

Time: 10/3/15 1:47 PM
Description: Ticking player

java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
    at java.util.ArrayList$Itr.next(Unknown Source)
    at net.malisis.core.util.RaytraceBlock.getClosest(RaytraceBlock.java:234)
    at net.malisis.core.util.RaytraceBlock.trace(RaytraceBlock.java:218)
    at net.malisis.doors.door.block.Door.func_149731_a(Door.java:369)
    at net.minecraft.world.World.func_147447_a(World.java:1221)
    at net.minecraft.world.World.func_72901_a(World.java:1029)
    at Reika.DragonAPI.Libraries.ReikaPlayerAPI.getLookedAtBlock(ReikaPlayerAPI.java:107)
    at Reika.ChromatiCraft.Auxiliary.ExplorationMonitor.tick(ExplorationMonitor.java:42)
    at Reika.DragonAPI.Auxiliary.Trackers.TickRegistry.playerTick(TickRegistry.java:47)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_404_TickRegistry_playerTick_PlayerTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at cpw.mods.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:345)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:220)
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295)
    at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303)
    at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
    at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Dominance** [comment]
So I take it you updated mods to see if the issue was resolved?

**Comment by Dominance** [comment]
Also what was around you, what where you doing also Can you replicate this 100% of the time?

**Comment by Eliteneet** [comment]
Yes I updated the mods to see if the issue was resolved.
I can count on it happening atleast once a session, it happens as I'm interacting with the door or when I turn to look at the door.

![firstdoor](https://cloud.githubusercontent.com/assets/2501786/10265184/54b49770-69da-11e5-980a-68b0311cbac5.png)
![firstdoor2](https://cloud.githubusercontent.com/assets/2501786/10265185/5b057a04-69da-11e5-89a7-3f70b8de26e9.png)

And a side note, my Railcraft recipes have relocked. This world was started before the changes to the tech tree and now I can't unlock them, is there a command to run to do that?

**Comment by Dominance** [comment]
On the side note. The quest gates are tracked by HQM and Progression/Chairs are from a different mod. If you are able to load up into creative. use the command /progression reset with editing enabled. https://github.com/Beyond-Reality/Beyond-Reality-Divergence/blob/master/config/progression/options.cfg#L5 This will reset all of your progression/research but all the quest gates will remain open. Just simply go punch/sit in all the chairs to regain your progression.

**Comment by Eliteneet** [comment]
Thanks, appreciated.

**Comment by Dominance** [comment]
Talked to Ordinastie about this. It will be fixed in the next upcoming malisis doors release. Will keep it open until it is included in Divergence,

**Comment by Dominance** [comment]
Fixed Next version 1.2.7
