### ISSUE TITLE
crashed whilst mining

### ISSUE THREAD

**Issue by hmbigburt** [Beyond-Reality/Beyond-Reality-Divergence#219]
for some reason it crashed and now it crashes every time it loads the area im mining in
http://pastebin.com/T4XPGD8A
http://pastebin.com/aaqT4CEH

let me know if these are not the right reports im trying pastebin for 1st time

**Comment by vagaprime** [comment]
I was getting the same problem before after shift clicking some stuff into a wooden hopper near my millstone.

**Comment by mrbaggins** [comment]
Yeah, my CM exception was near my millstone. I suspect it's sounds are breaking something.

**Comment by b0bst3r** [comment]
Try removing this optional mod SoundFilters-0.8_for_1.7.X.jar

**Comment by Dominance** [comment]
Already have confirmed it is not sound filters. Happens without it being installed. The only thing these crashes have in common is the mill stone being active around the player. @draco18s May be a issue just never reported before?

**Comment by Draco18s** [comment]
Its possible.  But it confuses me as to what's going on.
If you'd like I can compile up a version without sounds.  Orr... let me see if I can configurify this.

**Comment by Draco18s** [comment]
10.17.0c uploaded; should fix the problem and offers a config option to disable the mill sound

**Comment by mrbaggins** [comment]
Just to add insult to injury: CME whilst mining, nowhere near a mill. Was as I was hitting (not the breaking, just hitting) a hard gold ore. Had been hitting them for a few minutes when it hit.

```
[21/10/2015 16:34:46 PM] java.util.ConcurrentModificationException
[21/10/2015 16:34:46 PM]    at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~    [?:1.8.0_60]
[21/10/2015 16:34:46 PM]    at java.util.HashMap$KeyIterator.next(Unknown Source) ~[?:1.8.0_60]
[21/10/2015 16:34:46 PM]    at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:269) ~[mn.class:?]
[21/10/2015 16:34:46 PM]    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:648) ~[MinecraftServer.class:?]
[21/10/2015 16:34:46 PM]    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~     [MinecraftServer.class:?]
[21/10/2015 16:34:46 PM]    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) ~[bsx.class:?]
[21/10/2015 16:34:46 PM]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
[21/10/2015 16:34:46 PM]    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
```

**Comment by Draco18s** [comment]
What version of Hard Ores?

**Comment by mrbaggins** [comment]
1.2.6.3 modpack version. Was hitting gold, was a pretty full block but I'd hit it 3 or 4 times already.

**Comment by Draco18s** [comment]
Heh, sorry, doesn't help me figure out if that is before or after my latest fix. Dom?

**Comment by mrbaggins** [comment]
Remote desktop'd in, looks like 7.13.0a for the mod. The config file has "S:GENERAL=4.10"

**Comment by Draco18s** [comment]
Ah, ok, then that's pre-fix. v10 fixes it.

**Comment by Dominance** [comment]
Yeah the latest version that includes v10 is not yet released.
