### ISSUE TITLE
Crash on Chunk Generation - 

### ISSUE THREAD

**Issue by devanchya** [Beyond-Reality/Beyond-Reality-Divergence#284]
Brand new, fresh install of 1.2.7.1 - 

Time: 17/01/16 01:09
Description: Exception ticking world

java.lang.IllegalStateException: TickNextTick list out of synch
        at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:684)
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:279)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:931)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
        at java.lang.Thread.run(Thread.java:745)

Appears to be related to chunk generation.

Removed logs, no longer required.

**Comment by devanchya** [comment]
Track down to being due to issue #289 at https://gitlab.prok.pw/KCauldron/KCauldron/issues/289
