### ISSUE TITLE
Exception getting block type in world

### ISSUE THREAD

**Issue by Dr-MAD6969** [Beyond-Reality/Beyond-Reality-Divergence#357]
A player moving into an area, or loading a chuck completely crashes the server.

Deleting the player files resets them to be able to go back to spawn, but any player returning to the area causes the server to crash.

[00:10:08] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception getting block type in world
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.jav                                                                                                                                                             a:631) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(Dedicated                                                                                                                                                             Server.java:334) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.jav                                                                                                                                                             a:547) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [M                                                                                                                                                             inecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)                                                                                                                                                              [li.class:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
        at java.util.ArrayList.elementData(ArrayList.java:418) ~[?:1.8.0_91]
        at java.util.ArrayList.set(ArrayList.java:446) ~[?:1.8.0_91]
        at net.minecraft.world.chunk.storage.RegionFile.<init>(RegionFile.java:9                                                                                                                                                             0) ~[aqh.class:?]
        at net.minecraft.world.chunk.storage.RegionFileCache.func_76550_a(Source                                                                                                                                                             File:60) ~[aqj.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.chunkExists(AnvilC                                                                                                                                                             hunkLoader.java:71) ~[aqk.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderSe                                                                                                                                                             rver.java:117) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProvide                                                                                                                                                             rServer.java:101) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProvide                                                                                                                                                             rServer.java:199) ~[ms.class:?]
        at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
        at net.minecraft.world.World.func_147439_a(World.java:345) ~[ahb.class:?                                                                                                                                                             ]
        at net.minecraft.block.BlockGrass.func_149674_a(BlockGrass.java:57) ~[al                                                                                                                                                             h.class:?]
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:391) ~                                                                                                                                                             [mt.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183) ~[                                                                                                                                                             mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.jav                                                                                                                                                             a:625) ~[MinecraftServer.class:?]
        ... 4 more
[00:10:08] [Server thread/ERROR]: This crash report has been saved to:   
[crash-2017-11-23_00.10.08-server.txt](https://github.com/Beyond-Reality/Beyond-Reality-Divergence/files/1498301/crash-2017-11-23_00.10.08-server.txt)

./crash-reports/crash-2017-11-23_00.10.08-server.txt

**Comment by Dominance** [comment]
Best I can say is try to toggle on kill errored ticking enitiy via the forge config or use world edit to remove the black/entity that is causing the crash.

**Comment by Dr-MAD6969** [comment]
Thanks.  I'll see what I can do.

**Comment by Dr-MAD6969** [comment]
The forge config setting change did not fix it, but this weekend, I'll try to find the time to go through the world and delete the  corrupted chunks.

Thanks again for the help.

**Comment by Dr-MAD6969** [comment]
I do not know what caused it, but deleting the "missing/corrupt sections seemed to do the trick.
